version: '3.8'

services:
  scribbletune02:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      # Mount the output directory for generated MIDI files
      - ./duo:/app/duo
      # Mount the config file for live updates
      - ./db.json:/app/db.json
      # Mount frontend source for live development
      - ./frontend/src:/app/src
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s